server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&sharacterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wddlhyss.springcloud.entities   #所有entity别名类所在包
